
const DATA_KEY='leuchtfeuer_data_v1';
let data=load();
function load(){try{let x=localStorage.getItem(DATA_KEY);return x?JSON.parse(x):structuredClone(window.DEFAULT_DATA)}catch(e){return structuredClone(window.DEFAULT_DATA)}}
function save(){localStorage.setItem(DATA_KEY,JSON.stringify(data));toast('Gespeichert ✓')}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function login(){const p=document.getElementById('password').value;const saved=localStorage.getItem('lf_admin_pw')||'leuchtfeuer123';if(p===saved){sessionStorage.lf_admin='1';showApp()}else alert('Passwort falsch. Standard im statischen Paket: leuchtfeuer123')}
function logout(){sessionStorage.removeItem('lf_admin');location.reload()}
function showApp(){document.getElementById('login').style.display='none';document.getElementById('app').style.display='grid';renderAll()}
if(sessionStorage.lf_admin==='1')showApp();
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.style.display='none');document.getElementById('tab-'+b.dataset.tab).style.display='block';document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderAll()}));
function renderAll(){renderHours();renderMenu();renderOffers();renderEvents();renderSocial();renderSettings()}
function renderHours(){document.getElementById('hours-editor').innerHTML=data.hours.map((h,i)=>`<div class="panel"><div class="form-grid"><div class="field"><label>Tag</label><input data-h="${i}" data-k="day" value="${esc(h.day)}"></div><div class="field"><label>Geschlossen</label><select data-h="${i}" data-k="closed"><option value="false" ${!h.closed?'selected':''}>Nein</option><option value="true" ${h.closed?'selected':''}>Ja</option></select></div><div class="field"><label>Öffnet</label><input type="time" data-h="${i}" data-k="open" value="${esc(h.open)}"></div><div class="field"><label>Schließt</label><input type="time" data-h="${i}" data-k="close" value="${esc(h.close)}"></div></div></div>`).join('')}
function saveHours(){document.querySelectorAll('[data-h]').forEach(el=>{let i=+el.dataset.h,k=el.dataset.k;data.hours[i][k]=k==='closed'?el.value==='true':el.value});save()}
function renderMenu(){document.getElementById('menu-editor').innerHTML=data.menu.map((m,i)=>`<tr><td><input data-m="${i}" data-k="category" value="${esc(m.category)}"></td><td><input data-m="${i}" data-k="name" value="${esc(m.name)}"></td><td><input data-m="${i}" data-k="note" value="${esc(m.note)}"></td><td><input data-m="${i}" data-k="price" value="${esc(m.price)}"></td><td><button class="btn danger" onclick="removeMenu(${i})">×</button></td></tr>`).join('')}
function saveMenu(){document.querySelectorAll('[data-m]').forEach(el=>data.menu[+el.dataset.m][el.dataset.k]=el.value);save();renderMenu()}
function addMenu(){data.menu.push({category:'Neu',name:'Neuer Artikel',price:'0,00 €',note:''});renderMenu()}
function removeMenu(i){data.menu.splice(i,1);save();renderMenu()}
function renderOffers(){document.getElementById('offers-editor').innerHTML=data.offers.map((o,i)=>`<div class="panel"><div class="form-grid"><div class="field"><label>Titel</label><input data-o="${i}" data-k="title" value="${esc(o.title)}"></div><div class="field"><label>Preis</label><input data-o="${i}" data-k="price" value="${esc(o.price)}"></div><div class="field full"><label>Text</label><textarea data-o="${i}" data-k="text">${esc(o.text)}</textarea></div><div class="field"><label>Aktiv</label><select data-o="${i}" data-k="active"><option value="true" ${o.active?'selected':''}>Ja</option><option value="false" ${!o.active?'selected':''}>Nein</option></select></div></div><button class="btn danger" onclick="removeOffer(${i})" style="margin-top:12px">Angebot löschen</button></div>`).join('')}
function saveOffers(){document.querySelectorAll('[data-o]').forEach(el=>data.offers[+el.dataset.o][el.dataset.k]=el.dataset.k==='active'?el.value==='true':el.value);save()}
function addOffer(){data.offers.push({title:'Neues Angebot',text:'Beschreibung',price:'0,00 €',active:false});save();renderOffers()}
function removeOffer(i){data.offers.splice(i,1);save();renderOffers()}
function renderEvents(){document.getElementById('events-editor').innerHTML=data.events.map((e,i)=>`<div class="panel"><div class="form-grid"><div class="field"><label>Datum / Tag</label><input data-e="${i}" data-k="date" value="${esc(e.date)}"></div><div class="field"><label>Titel</label><input data-e="${i}" data-k="title" value="${esc(e.title)}"></div><div class="field full"><label>Beschreibung</label><textarea data-e="${i}" data-k="text">${esc(e.text)}</textarea></div><div class="field"><label>Aktiv</label><select data-e="${i}" data-k="active"><option value="true" ${e.active?'selected':''}>Ja</option><option value="false" ${!e.active?'selected':''}>Nein</option></select></div></div><button class="btn danger" onclick="removeEvent(${i})" style="margin-top:12px">Veranstaltung löschen</button></div>`).join('')}
function saveEvents(){document.querySelectorAll('[data-e]').forEach(el=>data.events[+el.dataset.e][el.dataset.k]=el.dataset.k==='active'?el.value==='true':el.value);save()}
function addEvent(){data.events.push({date:'Freitag',title:'Neue Veranstaltung',text:'Beschreibung',active:false});save();renderEvents()}
function removeEvent(i){data.events.splice(i,1);save();renderEvents()}
function renderSocial(){for(const id of ['instagram','facebook','latestInstagram','latestFacebook'])document.getElementById(id).value=data.site[id]||''}
function saveSocial(){['instagram','facebook','latestInstagram','latestFacebook'].forEach(id=>data.site[id]=document.getElementById(id).value.trim());save()}
function renderSettings(){for(const id of ['siteName','tagline','description','address','zipcity','phone','email']){const key={siteName:'name',tagline:'tagline',description:'description',address:'address',zipcity:'zipcity',phone:'phone',email:'email'}[id];document.getElementById(id).value=data.site[key]||''}}
function saveSettings(){Object.assign(data.site,{name:siteName.value,tagline:tagline.value,description:description.value,address:address.value,zipcity:zipcity.value,phone:phone.value,email:email.value});save()}
function exportData(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='leuchtfeuer-daten.json';a.click();URL.revokeObjectURL(a.href)}
function importData(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{data=JSON.parse(r.result);save();renderAll();toast('Import erfolgreich ✓')}catch(err){alert('Ungültige JSON-Datei')}};r.readAsText(f)}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
window.login=login;window.logout=logout;window.saveHours=saveHours;window.saveMenu=saveMenu;window.addMenu=addMenu;window.removeMenu=removeMenu;window.addOffer=addOffer;window.removeOffer=removeOffer;window.addEvent=addEvent;window.removeEvent=removeEvent;window.saveSocial=saveSocial;window.saveSettings=saveSettings;window.exportData=exportData;window.importData=importData;
